graph LR
A[<img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1MCIgaGVpZ2h0PSI1MCI+CjxwYXRoIGQ9Ik0xMC4xMTIgMTAuMTEyYy0uNjY2IDAtMS4xMTIuNTY2LTEuMTEyIDEuMTEyYy0uNjY2IDAtMS4xMTIuNTY2LTEuMTEyIDEuMTEyYzAtLjY2Ni41NjYtMS4xMTIuNTY2LTEuMTEyIDEuMTEyQzEwLjExMiA0LjU2NiAxMC4xMTIgNC41NjYgMTAuMTEyIDUuNTY2QzQuNTY2IDUuNTY2IDQuNTY2IDEwLjExMiA1LjU2NiAxMC4xMTJ6IiBmaWxsPSIjZmZmZmZmIi8+Cjwvc3ZnPg=="/>] --> B
