%%{init:{"theme":"dark","flowchart":{"curve":"linear"}}}%% 

flowchart BT
    Jedan[Jedan\nChristmas] -->|KomentarA| Dva[Neštonešto]
    Dva --> Tri{Let me think}
    Tri -->|Broj4| Četiri[LeKomentar]
    Tri -->|PremaDva| Pet[Tekst5]
    Tri -->|Tri| Šest[fa:fa-car Car]

Pet[<img src='https://raw.githubusercontent.com/matthewhand/mermaid-diagrams/main/Arch_Amazon-Simple-Storage-Service_64.png' width='40' /> \nasd]

Šest([<img src='https://icon-library.com/images/small-icon-png/small-icon-png-6.jpg' width='40' /> QWE]) 

Tri[(<img src='https://icon-library.com/images/small-icon-png/small-icon-png-6.jpg' width='40',height='40' />)]
